{"name": "test_valid_sign_in[chrome]", "status": "broken", "statusDetails": {"message": "TypeError: capture_screenshot() takes 1 positional argument but 2 were given", "trace": "self = <Tests.UI_Test.test_login.TestLogin object at 0x000001876EB55400>\nsetup_pages = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"436e40e90918a8e23b0c9e8254fc1d19\")>, <UI_Pages.loginPage.Log...ges.cartPage.CartPage object at 0x000001876F48C3B0>, <UI_Pages.checkoutPage.CheckoutPage object at 0x000001876F48C410>)\nui_data = {'INVALID PASSWORD': 'Admin@123', 'PASSWORD': 'secret_sauce', 'Zipcode': '987867', 'firstName': 'Harry', ...}\nassertion_data = {'cart_heading': 'Shipping', 'expected_text': 'Epic sadface: Username and password do not match any user in this service', 'expected_url': 'https://www.saucedemo.com/inventory.html', 'product_name': 'Sauce Labs Backpack', ...}\nlogger_setup = None, request = <FixtureRequest for <Function test_valid_sign_in[chrome]>>\ninit_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"436e40e90918a8e23b0c9e8254fc1d19\")>, browser = 'chrome'\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"browser\", [\"chrome\" ])\n    def test_valid_sign_in(self, setup_pages, ui_data, assertion_data, logger_setup,request, init_driver, browser):\n        logging.getLogger(\"root\").info(\"Starting test_valid_signin\")\n        allure.attach('Starting test_valid_signin', attachment_type=allure.attachment_type.TEXT)\n        driver, login_page, _, _ = setup_pages\n        logging.getLogger(\"root\").info(\"Logging with valid credentials\")\n        allure.attach('Logging with valid credentials', attachment_type=allure.attachment_type.TEXT)\n        self.login_and_assert(login_page, driver, ui_data, assertion_data)\n        allure.attach('Logging successfully', attachment_type=allure.attachment_type.TEXT)\n        logging.getLogger(\"root\").info(\"Ending test_valid_signin\")\n        if request.session.testsfailed > 0:\n>           screenshot_path = capture_screenshot(driver, \"test_valid_sign_in\")\nE           TypeError: capture_screenshot() takes 1 positional argument but 2 were given\n\nTests\\UI_Test\\test_login.py:25: TypeError"}, "attachments": [{"source": "8eb8df65-8a0a-402b-b791-4f53629bc19b-attachment.txt", "type": "text/plain"}, {"source": "7099e46b-e367-425b-ba84-5db98ad72275-attachment.txt", "type": "text/plain"}, {"source": "72a128c8-6428-4dd8-8953-c93ce2a1c2a3-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "07f6291f-29a1-418f-83ca-fa7cbf873a57-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1715244566973, "stop": 1715244567601, "uuid": "43107dbc-e88a-4c9d-884b-d90351c53f6e", "historyId": "f1aebfe96b81d111413432f15a02e381", "testCaseId": "c45d73e905ffe70f729e3c177209e9eb", "fullName": "Tests.UI_Test.test_login.TestLogin#test_valid_sign_in", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests.UI_Test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Feuji-006L-R"}, {"name": "thread", "value": "23560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.UI_Test.test_login"}]}