{"name": "test_invalid_sign_in[chrome]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\n  - https://www.saucedemo.com/inventory.html\n  ?                           --------------\n  + https://www.saucedemo.com/", "trace": "self = <Tests.UI_Test.test_login.TestLogin object at 0x000001B55DF25730>\nsetup_pages = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"489b947b4d7ea92661c8cede429f8cba\")>, <UI_Pages.loginPage.Log...ges.cartPage.CartPage object at 0x000001B55E8A58B0>, <UI_Pages.checkoutPage.CheckoutPage object at 0x000001B55E8C20F0>)\nui_data = {'INVALID PASSWORD': 'Admin@123', 'PASSWORD': 'secret_sauce', 'Zipcode': '987867', 'firstName': 'Harry', ...}\nassertion_data = {'cart_heading': 'Shipping', 'expected_text': 'Epic sadface: Username and password do not match any user in this service', 'expected_url': 'https://www.saucedemo.com/inventory.html', 'product_name': 'Sauce Labs Backpack', ...}\ninit_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"489b947b4d7ea92661c8cede429f8cba\")>, logger_setup = None, browser = 'chrome'\n\n    @pytest.mark.run(order=7)\n    @pytest.mark.parametrize(\"browser\", [\"chrome\"])\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_invalid_sign_in(self, setup_pages, ui_data, assertion_data, init_driver, logger_setup, browser):\n        logging.getLogger(\"root\").info(\"Starting test_invalid_signin\")\n        allure.attach('Starting test_invalid_signin', attachment_type=allure.attachment_type.TEXT)\n        driver, login_page, _, _ = setup_pages\n        logging.getLogger(\"root\").info(\"Logging with invalid credentials\")\n        allure.attach('Logging with invalid credentials', attachment_type=allure.attachment_type.TEXT)\n        login_page.click_login(ui_data['userName'], ui_data['INVALID PASSWORD'])\n>       assert driver.current_url == assertion_data['expected_url']\nE       AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\nE         - https://www.saucedemo.com/inventory.html\nE         ?                           --------------\nE         + https://www.saucedemo.com/\n\nTests\\UI_Test\\test_login.py:35: AssertionError"}, "attachments": [{"source": "a354f712-b5d2-4c3b-91e4-3b6f0fdf4769-attachment.txt", "type": "text/plain"}, {"source": "e0e19218-22b0-434b-9d9a-a2bab9f940fc-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "560dd49a-c50b-4d44-af23-8e29c8157852-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1715134575950, "stop": 1715134576942, "uuid": "e3a5cdc2-4d17-48fd-b857-26fac0a03f8b", "historyId": "48fa2a146192f03756034ec19e88f559", "testCaseId": "b7222e4c40dbe92f2068b4c04f70d99c", "fullName": "Tests.UI_Test.test_login.TestLogin#test_invalid_sign_in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "run(order=7)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests.UI_Test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Feuji-006L-R"}, {"name": "thread", "value": "3008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.UI_Test.test_login"}]}