{"name": "test_invalid_sign_in[chrome]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\n  - https://www.saucedemo.com/inventory.html\n  ?                           --------------\n  + https://www.saucedemo.com/", "trace": "self = <Tests.UI_Test.test_login.TestLogin object at 0x0000022B66CFD850>\nsetup_pages = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"345ad18c9401139b4fd17ad64cd088c1\")>, <UI_Pages.loginPage.Log...ges.cartPage.CartPage object at 0x0000022B6666C530>, <UI_Pages.checkoutPage.CheckoutPage object at 0x0000022B66CFFE90>)\nui_data = {'INVALID PASSWORD': 'Admin@123', 'PASSWORD': 'secret_sauce', 'Zipcode': '987867', 'firstName': 'Harry', ...}\nassertion_data = {'cart_heading': 'Shipping', 'expected_text': 'Epic sadface: Username and password do not match any user in this service', 'expected_url': 'https://www.saucedemo.com/inventory.html', 'product_name': 'Sauce Labs Backpack', ...}\ninit_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"345ad18c9401139b4fd17ad64cd088c1\")>, logger_setup = None, browser = 'chrome'\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"browser\", [\"chrome\"])\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_invalid_sign_in(self, setup_pages, ui_data, assertion_data, init_driver, logger_setup, browser):\n        logging.getLogger(\"root\").info(\"Starting test_invalid_signin\")\n        allure.attach('Starting test_invalid_signin', attachment_type=allure.attachment_type.TEXT)\n        driver, login_page, _, _ = setup_pages\n        login_page.click_login(ui_data['userName'], ui_data['INVALID PASSWORD'])\n        expected_url = assertion_data.get('expected_url')\n        if expected_url is not None:\n>           assert driver.current_url == expected_url\nE           AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\nE             - https://www.saucedemo.com/inventory.html\nE             ?                           --------------\nE             + https://www.saucedemo.com/\n\nTests\\UI_Test\\test_login.py:76: AssertionError"}, "attachments": [{"source": "30e4187f-9ad0-4604-b026-f2e687778d72-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "131e4d20-3cff-4a58-ba16-1af2e59317cc-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ae9c13ab-9765-4497-b63c-5b6e36a1a6ab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1715607605318, "stop": 1715607606350, "uuid": "d5b88cd3-8f71-45ee-8481-4fbd3ab7295f", "historyId": "48fa2a146192f03756034ec19e88f559", "testCaseId": "b7222e4c40dbe92f2068b4c04f70d99c", "fullName": "Tests.UI_Test.test_login.TestLogin#test_invalid_sign_in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests.UI_Test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Feuji-006L-R"}, {"name": "thread", "value": "20352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.UI_Test.test_login"}]}