{"name": "test_invalid_sign_in[chrome]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\n  - https://www.saucedemo.com/inventory.html\n  ?                           --------------\n  + https://www.saucedemo.com/", "trace": "self = <Tests.UI_Test.test_login.TestLogin object at 0x000002841CF36900>, request = <FixtureRequest for <Function test_invalid_sign_in[chrome]>>\nsetup_pages = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"9dbcd4671db6cb625254de8a0e4b6900\")>, <UI_Pages.loginPage.Log...ges.cartPage.CartPage object at 0x000002841D33EB10>, <UI_Pages.checkoutPage.CheckoutPage object at 0x000002841D33F290>)\nui_data = {'INVALID PASSWORD': 'Admin@123', 'PASSWORD': 'secret_sauce', 'Zipcode': '987867', 'firstName': 'Harry', ...}\nassertion_data = {'cart_heading': 'Shipping', 'expected_text': 'Epic sadface: Username and password do not match any user in this service', 'expected_url': 'https://www.saucedemo.com/inventory.html', 'product_name': 'Sauce Labs Backpack', ...}\ninit_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9dbcd4671db6cb625254de8a0e4b6900\")>, logger_setup = None, browser = 'chrome'\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize(\"browser\", [\"chrome\"])\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_invalid_sign_in(self,request, setup_pages, ui_data, assertion_data, init_driver, logger_setup, browser):\n        logging.getLogger(\"root\").info(\"Starting test_invalid_signin\")\n        allure.attach('Starting test_invalid_signin', attachment_type=allure.attachment_type.TEXT)\n        driver, login_page, _, _ = setup_pages\n        login_page.click_login(ui_data['userName'], ui_data['INVALID PASSWORD'])\n        expected_url = assertion_data.get('expected_url')\n        if expected_url is not None:\n>           assert driver.current_url == expected_url\nE           AssertionError: assert 'https://www.saucedemo.com/' == 'https://www....nventory.html'\nE             - https://www.saucedemo.com/inventory.html\nE             ?                           --------------\nE             + https://www.saucedemo.com/\n\nTests\\UI_Test\\test_login.py:38: AssertionError"}, "attachments": [{"source": "425250a2-cb94-4ca9-9946-21b993336337-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "0d44bc1d-65f8-42a0-b3b1-b5fe4408c50d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1715251622012, "stop": 1715251622661, "uuid": "45384597-c5d6-4769-b907-aa2e2f6f63d8", "historyId": "48fa2a146192f03756034ec19e88f559", "testCaseId": "b7222e4c40dbe92f2068b4c04f70d99c", "fullName": "Tests.UI_Test.test_login.TestLogin#test_invalid_sign_in", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests.UI_Test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Feuji-006L-R"}, {"name": "thread", "value": "3024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.UI_Test.test_login"}]}